# Generated by Django 4.2.13 on 2026-04-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timeout', models.PositiveIntegerField(help_text='Countdown duration in seconds.')),
                ('alert_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('down', 'Down')], default='active', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
